AWSTemplateFormatVersion: "2010-09-09"
Description: "Funciones Lambda para microservicios de gestión de libros con VPC"

Parameters:
  ECRRepository:
    Type: String
    Default: book-manager

  CreateBookImageTag:
    Type: String
    Default: create_book

  GetBooksImageTag:
    Type: String
    Default: get_books

  GetBookImageTag:
    Type: String
    Default: get_book

  UpdateBookImageTag:
    Type: String
    Default: update_book

  DeleteBookImageTag:
    Type: String
    Default: delete_book

  DBHost:
    Type: String
    Description: RDS PostgreSQL Endpoint

  DBName:
    Type: String
    Default: bookmanagerdb

  DBUser:
    Type: String
    Default: postgres

  DBPass:
    Type: String
    NoEcho: true

  VpcId:
    Type: AWS::EC2::VPC::Id

  VpcCidr:
    Type: String
    Default: "172.31.0.0/16"

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

  DBSecurityGroupId:
    Type: String

Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group para Lambdas en VPC
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  LambdaToDBAccess:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow Lambda to access RDS
      GroupId: !Ref DBSecurityGroupId
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref LambdaSecurityGroup

  CreateBookLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: book-manager-create
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}:${CreateBookImageTag}"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          DB_TYPE: postgres
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASS: !Ref DBPass
          DB_HOST: !Ref DBHost
          DB_PORT: "5432"
          LAMBDA_FUNCTION: create
      Architectures: [x86_64]
      VpcConfig:
        SubnetIds: !Ref SubnetIds
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup

  GetBooksLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: book-manager-get-all
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}:${GetBooksImageTag}"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          DB_TYPE: postgres
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASS: !Ref DBPass
          DB_HOST: !Ref DBHost
          DB_PORT: "5432"
          LAMBDA_FUNCTION: get_all
      Architectures: [x86_64]
      VpcConfig:
        SubnetIds: !Ref SubnetIds
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup

  GetBookLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: book-manager-get
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}:${GetBookImageTag}"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          DB_TYPE: postgres
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASS: !Ref DBPass
          DB_HOST: !Ref DBHost
          DB_PORT: "5432"
          LAMBDA_FUNCTION: get
      Architectures: [x86_64]
      VpcConfig:
        SubnetIds: !Ref SubnetIds
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup

  UpdateBookLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: book-manager-update
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}:${UpdateBookImageTag}"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          DB_TYPE: postgres
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASS: !Ref DBPass
          DB_HOST: !Ref DBHost
          DB_PORT: "5432"
          LAMBDA_FUNCTION: update
      Architectures: [x86_64]
      VpcConfig:
        SubnetIds: !Ref SubnetIds
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup

  DeleteBookLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: book-manager-delete
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}:${DeleteBookImageTag}"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          DB_TYPE: postgres
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASS: !Ref DBPass
          DB_HOST: !Ref DBHost
          DB_PORT: "5432"
          LAMBDA_FUNCTION: delete
      Architectures: [x86_64]
      VpcConfig:
        SubnetIds: !Ref SubnetIds
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup

  CreateBookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/book-manager-create
      RetentionInDays: 7

  GetBooksLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/book-manager-get-all
      RetentionInDays: 7

  GetBookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/book-manager-get
      RetentionInDays: 7

  UpdateBookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/book-manager-update
      RetentionInDays: 7

  DeleteBookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/book-manager-delete
      RetentionInDays: 7

Outputs:
  CreateBookLambdaArn:
    Value: !GetAtt CreateBookLambda.Arn

  GetBooksLambdaArn:
    Value: !GetAtt GetBooksLambda.Arn

  GetBookLambdaArn:
    Value: !GetAtt GetBookLambda.Arn

  UpdateBookLambdaArn:
    Value: !GetAtt UpdateBookLambda.Arn

  DeleteBookLambdaArn:
    Value: !GetAtt DeleteBookLambda.Arn

  LambdaSecurityGroupId:
    Value: !Ref LambdaSecurityGroup
