AWSTemplateFormatVersion: "2010-09-09"
Description: "ECR Repository para Book Manager"

Parameters:
  RepositoryName:
    Type: String
    Default: book-manager
    Description: Nombre del repositorio ECR

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration:
        ScanOnPush: false
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Mantener solo las últimas 2 imágenes",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 2
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Description: URI del repositorio ECR
    Value: !GetAtt ECRRepository.RepositoryUri

  RepositoryName:
    Description: Nombre del repositorio
    Value: !Ref RepositoryName

  RepositoryArn:
    Description: ARN del repositorio
    Value: !GetAtt ECRRepository.Arn
